// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5p5geBlCIWVYLdOOJZE2fH-6t_rJsQYI',
    appId: '1:565227006204:web:eea994d919be14549e8f79',
    messagingSenderId: '565227006204',
    projectId: 'key-acre-347214',
    authDomain: 'key-acre-347214.firebaseapp.com',
    databaseURL: 'https://key-acre-347214-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'key-acre-347214.appspot.com',
    measurementId: 'G-VL4WTW1PFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw8LMClOncDuU7_4Y1wyHL-gvVWbxWIRw',
    appId: '1:565227006204:android:5a95f5788171d80f9e8f79',
    messagingSenderId: '565227006204',
    projectId: 'key-acre-347214',
    databaseURL: 'https://key-acre-347214-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'key-acre-347214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKwIi_LHOsfWGQNiZJcH_ocCm5-ek4xI',
    appId: '1:565227006204:ios:6b6b692b4f9e3b759e8f79',
    messagingSenderId: '565227006204',
    projectId: 'key-acre-347214',
    databaseURL: 'https://key-acre-347214-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'key-acre-347214.appspot.com',
    iosClientId: '565227006204-i3nchhp2j2n98d8977r9hpmjcd8c6ekm.apps.googleusercontent.com',
    iosBundleId: 'com.example.croissAcq',
  );
}
